// IP-SAKTI Sahayak — Mock Legal Corpus
// All records are strictly labelled as MOCK in accordance with PRD and SIH 2026 guidelines.
// Grounded in open, authoritative public sources: TKDL, India Code, IP India, and NBA.

export type AuthoritativeDatasetKey = 'tkdl' | 'indiacode' | 'ipindia' | 'nbaindia' | 'international';

export interface MockSourceDocument {
  source_id: string;
  authority: string;
  title: string;
  jurisdiction: 'India' | 'International' | 'Both';
  topic:
    | 'Patentability'
    | 'Traditional Knowledge / TKDL'
    | 'ABS / Biodiversity'
    | 'Drugs & Cosmetics'
    | 'Food / Ayurveda-Aahar'
    | 'Cosmetics'
    | 'International / Export';
  provision: string;
  version_date: string;
  content: string;
  summary: string;
  url_placeholder: string;
  dataset_origin: AuthoritativeDatasetKey;
  authoritative_source_url: string;
  tags: string[];
  is_mock: boolean;
}

export const MOCK_CORPUS: MockSourceDocument[] = [
  {
    source_id: 'MOCK-IN-001',
    authority: 'Indian Patent Office (CGPDTM) / Ministry of Commerce & Industry',
    title: 'The Patents Act, 1970 (As Amended 2005) — Traditional Knowledge Exclusion',
    jurisdiction: 'India',
    topic: 'Traditional Knowledge / TKDL',
    provision: 'Section 3(p)',
    version_date: '2005-01-01',
    summary: 'An invention which in effect is traditional knowledge or an aggregation/duplication of known properties is not patentable.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 3(p): The following are not inventions within the meaning of this Act: "an invention which in effect, is traditional knowledge or which is an aggregation or duplication of known properties of traditionally known component or components." Classical Ayurvedic formulations directly cited from authoritative texts (e.g. Charaka Samhita, Sushruta Samhita) fall squarely under this exclusion and cannot be patented as product claims without demonstrable novel synergistic modification or technological extraction.',
    url_placeholder: 'https://indiacode.nic.in/handle/123456789/1392',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in/handle/123456789/1392',
    tags: ['patent', 'traditional knowledge', 'charaka', 'sushruta', 'section 3p', 'ayurveda'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-002',
    authority: 'Indian Patent Office (CGPDTM)',
    title: 'The Patents Act, 1970 — Mere Admixture and Aggregation Exclusion',
    jurisdiction: 'India',
    topic: 'Patentability',
    provision: 'Section 3(e)',
    version_date: '2005-01-01',
    summary: 'A substance obtained by a mere admixture resulting only in aggregation of properties is not an invention.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 3(e): "a substance obtained by a mere admixture resulting only in the aggregation of the properties of the components thereof or a process for producing such substance" is non-patentable. To overcome Section 3(e), applicants must submit comparative experimental data establishing a synergistic therapeutic index (e.g. combination index < 1.0) rather than a simple mathematical sum of individual botanical actions.',
    url_placeholder: 'https://indiacode.nic.in/handle/123456789/1392',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in/handle/123456789/1392',
    tags: ['patent', 'admixture', 'synergy', 'herbal composition', 'section 3e'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-003',
    authority: 'Indian Patent Office (CGPDTM) / Supreme Court Precedent',
    title: 'The Patents Act, 1970 — Enhanced Efficacy Standard',
    jurisdiction: 'India',
    topic: 'Patentability',
    provision: 'Section 3(d) & Explanation',
    version_date: '2005-01-01',
    summary: 'Mere discovery of a new form of known substance without significant enhancement of therapeutic efficacy is non-patentable.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 3(d): "the mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance or the mere discovery of any new property or new use for a known substance..." For Ayurvedic extract fractions or polymorphs, applicants must establish demonstrable, statistically significant increase in therapeutic bio-efficacy over raw classical preparations.',
    url_placeholder: 'https://indiacode.nic.in/handle/123456789/1392',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in/handle/123456789/1392',
    tags: ['patent', 'efficacy', 'phytochemical', 'fraction', 'section 3d'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-004',
    authority: 'Indian Patent Office (CGPDTM)',
    title: 'The Patents Act, 1970 — Mandatory Biological Source Disclosure',
    jurisdiction: 'India',
    topic: 'ABS / Biodiversity',
    provision: 'Section 10(4)(d)(ii) & Form 1',
    version_date: '2005-01-01',
    summary: 'Patent specifications must disclose the source and geographical origin of biological material used.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 10(4)(d)(ii): Patent applications mentioning any biological material from India must declare the exact geographical source of collection in the complete specification and confirm whether National Biodiversity Authority (NBA) approval has been sought or obtained.',
    url_placeholder: 'https://ipindia.gov.in',
    dataset_origin: 'ipindia',
    authoritative_source_url: 'https://ipindia.gov.in',
    tags: ['biological material', 'patent disclosure', 'geographical origin', 'nba'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-005',
    authority: 'National Biodiversity Authority (NBA) / Ministry of Environment, Forest and Climate Change',
    title: 'Biological Diversity Act, 2002 — Commercial Utilization of Biological Resources',
    jurisdiction: 'India',
    topic: 'ABS / Biodiversity',
    provision: 'Section 3 & Section 6',
    version_date: '2004-04-15',
    summary: 'Foreign entities, NRIs, and Indian companies with foreign equity require prior NBA approval (Form I / Form III) before commercial access or patent filing.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 6(1): "No person shall apply for any intellectual property right, by whatever name called, in or outside India for any invention based on any research or information on a biological resource obtained from India without obtaining the previous approval of the National Biodiversity Authority." Application must be made under Form III prior to patent grant.',
    url_placeholder: 'https://nbaindia.org',
    dataset_origin: 'nbaindia',
    authoritative_source_url: 'https://nbaindia.org',
    tags: ['abs', 'nba', 'biodiversity act', 'form 3', 'benefit sharing', 'foreign equity'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-006',
    authority: 'State Biodiversity Boards (SBB) / NBA',
    title: 'Biological Diversity Act, 2002 — Prior Intimation by Indian Citizens & MSMEs',
    jurisdiction: 'India',
    topic: 'ABS / Biodiversity',
    provision: 'Section 7 & Section 24',
    version_date: '2004-04-15',
    summary: 'Indian citizens and entities without foreign participation must provide prior intimation to the concerned State Biodiversity Board before commercial utilization.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 7: Indian citizens, body corporates registered in India with zero foreign equity who obtain biological resources for commercial utilization must give prior intimation to the State Biodiversity Board (SBB). Vaidyas and local Hakims practicing indigenous medicine for personal or non-commercial healing are statutorily exempted.',
    url_placeholder: 'https://nbaindia.org',
    dataset_origin: 'nbaindia',
    authoritative_source_url: 'https://nbaindia.org',
    tags: ['sbb', 'state biodiversity board', 'indian citizens', 'ayurvedic vaidyas', 'commercial use'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-007',
    authority: 'National Biodiversity Authority (NBA)',
    title: 'Guidelines on Access and Benefit Sharing (ABS) Regulations',
    jurisdiction: 'India',
    topic: 'ABS / Biodiversity',
    provision: 'Regulation 2, 3 & Schedule I (ABS Percentages)',
    version_date: '2014-11-21',
    summary: 'Benefit sharing levies range from 0.1% to 0.5% of ex-factory sale price depending on annual turnover brackets.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] NBA ABS Guidelines 2014: For commercial utilization of Indian herbs/plants: Annual gross ex-factory sale up to INR 1 Crore = 0.1%; INR 1 to 3 Crore = 0.2%; Above INR 3 Crore = 0.5%. Cultivated medicinal plants purchased from registered farmers with traceability certificates enjoy streamlined fast-track ABS clearances.',
    url_placeholder: 'https://nbaindia.org',
    dataset_origin: 'nbaindia',
    authoritative_source_url: 'https://nbaindia.org',
    tags: ['abs levy', 'benefit sharing', 'ex-factory', 'cultivated herbs', 'traceability'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-008',
    authority: 'Ministry of AYUSH / Central Drugs Standard Control Organization (CDSCO)',
    title: 'Drugs & Cosmetics Act, 1940 — Definition of Classical Ayurvedic Drugs',
    jurisdiction: 'India',
    topic: 'Drugs & Cosmetics',
    provision: 'Section 3(a) & First Schedule',
    version_date: '1940-04-10',
    summary: 'Classical Ayurvedic medicines are manufactured strictly in accordance with formulations described in authoritative texts listed in the First Schedule.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 3(a): "Ayurvedic, Siddha or Unani (ASU) drug includes all medicines intended for internal or external use for or in the diagnosis, treatment, mitigation or prevention of disease or disorder in human beings or animals, and manufactured exclusively in accordance with the formulae described in the authoritative books of Ayurvedic, Siddha and Unani Tibb systems specified in the First Schedule (e.g. Charaka Samhita, Sushruta Samhita, Ashtanga Hridaya, Sahasrayogam, Sharngadhara Samhita, Bhasma Prakarana)."',
    url_placeholder: 'https://indiacode.nic.in/handle/123456789/2405',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in/handle/123456789/2405',
    tags: ['classical medicine', 'first schedule', 'charaka', 'sushruta', 'ashtanga hridaya', 'ayush license'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-009',
    authority: 'Ministry of AYUSH / State Licensing Authorities (SLA)',
    title: 'Drugs & Cosmetics Act, 1940 — Patent or Proprietary Ayurvedic Medicine',
    jurisdiction: 'India',
    topic: 'Drugs & Cosmetics',
    provision: 'Section 3(h) & Rule 158B',
    version_date: '2010-08-10',
    summary: 'Proprietary Ayurvedic medicines contain ingredients mentioned in First Schedule texts but formulated in novel combinations, rationales, or modern dosage forms.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Section 3(h): "Patent or Proprietary medicine in relation to Ayurvedic systems means a drug which is a remedy or prescription presented in any form not specified in the authoritative books of Ayurveda, but containing only such ingredients mentioned in the formulae described in the authoritative books of Ayurveda specified in the First Schedule." Rule 158B requires safety and published textual rationale or clinical pilot study for grant of manufacturing license from the State Licensing Authority.',
    url_placeholder: 'https://indiacode.nic.in/handle/123456789/2405',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in/handle/123456789/2405',
    tags: ['proprietary medicine', 'rule 158b', 'ayurvedic license', 'clinical safety', 'novel dosage'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-010',
    authority: 'Central Drugs Standard Control Organization (CDSCO)',
    title: 'Drugs and Cosmetics Rules — Phytopharmaceutical Drug Regulatory Pathway',
    jurisdiction: 'India',
    topic: 'Drugs & Cosmetics',
    provision: 'Rule 2(ee) & Schedule Y (Appendix I-B)',
    version_date: '2015-11-30',
    summary: 'Phytopharmaceuticals are purified, standardized fractions with minimum 4 active markers, requiring Phase I-III clinical trial clearance from DCGI.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Phytopharmaceutical Drugs: Defined as purified and standardized fraction with defined minimum four bio-active or phytochemical marker compounds (qualitatively and quantitatively assessed) of an extract of a medicinal plant or its part, for internal or external use of human beings. Regulated under CDSCO / DCGI with full preclinical toxicology and safety studies, eligible for product and process patent claims.',
    url_placeholder: 'https://indiacode.nic.in',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in',
    tags: ['phytopharmaceutical', 'cdsco', 'standardized fraction', 'dcgi', 'biomarkers', 'patentable'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-011',
    authority: 'Food Safety and Standards Authority of India (FSSAI) / Ministry of AYUSH',
    title: 'Food Safety and Standards (Ayurveda Aahar) Regulations, 2022',
    jurisdiction: 'India',
    topic: 'Food / Ayurveda-Aahar',
    provision: 'Regulation 3, 4, 6 & Schedule A',
    version_date: '2022-05-05',
    summary: 'Ayurveda Aahar covers food prepared in accordance with recipes or processes described in authoritative Ayurvedic texts, bearing the special Ayurveda Aahar logo.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] FSSAI Ayurveda Aahar Regulations 2022: Products intended for food and nutritional use prepared strictly according to Ayurvedic texts (Pathya/Ahara). Must not contain synthetic vitamins, minerals, or botanical extracts outside permitted schedules. Must display the dedicated Ayurveda Aahar logo. Cannot make medical treatment or disease cure claims (only physiological balance / wellness claims permitted).',
    url_placeholder: 'https://indiacode.nic.in/handle/123456789/2014',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in/handle/123456789/2014',
    tags: ['ayurveda aahar', 'fssai', 'nutraceutical', 'pathya', 'food safety', 'wellness claims'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-012',
    authority: 'Central Drugs Standard Control Organization (CDSCO) / BIS',
    title: 'Drugs & Cosmetics Rules — Ayurvedic Herbal Cosmetics & Toiletries',
    jurisdiction: 'India',
    topic: 'Cosmetics',
    provision: 'Schedule S & Rule 139 / Part XIII',
    version_date: '2020-12-15',
    summary: 'Herbal cosmetic products for skin, hair, and external grooming with permitted Ayurvedic actives under Cosmetics Rules 2020.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Ayurvedic Cosmetics: Products applied externally to cleanse, beautify, promote attractiveness or alter appearance containing classical or proprietary botanical actives. Regulated under Cosmetics Rules 2020 / State Licensing Authority. Prohibited from claiming systemic therapeutic anti-disease cures. Novel extraction methods or sustained-release formulations may be patentable as process/delivery systems.',
    url_placeholder: 'https://indiacode.nic.in',
    dataset_origin: 'indiacode',
    authoritative_source_url: 'https://indiacode.nic.in',
    tags: ['cosmetics', 'herbal cosmetic', 'skincare', 'state licensing', 'delivery system'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-013',
    authority: 'Council of Scientific and Industrial Research (CSIR) / Ministry of AYUSH',
    title: 'Traditional Knowledge Digital Library (TKDL) — Defensive Prior-Art Search Protocol',
    jurisdiction: 'India',
    topic: 'Traditional Knowledge / TKDL',
    provision: 'TKDL Prior Art Access Agreements & Examination Manual',
    version_date: '2022-08-20',
    summary: 'TKDL contains 34 million+ digitized pages translating ancient texts into IPC patent classifications to prevent biopiracy and improper patents globally.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] CSIR-TKDL Database: Translates Sanskrit, Arabic, Persian, Urdu, Tamil classical texts into 5 international languages (English, German, French, Japanese, Spanish) structured in IPC patent taxonomy. Patent examiners at USPTO, EPO, JPO, and IPO routinely cite TKDL to reject claims lacking novelty. Researchers must perform TKDL clearance before claiming patentability on herbal formulations.',
    url_placeholder: 'https://tkdl.res.in',
    dataset_origin: 'tkdl',
    authoritative_source_url: 'https://tkdl.res.in',
    tags: ['tkdl', 'csir', 'prior art', 'biopiracy', 'defensive publication', 'patent search'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-IN-014',
    authority: 'Indian Patent Office (CGPDTM)',
    title: 'Guidelines for Examination of Patent Applications on Traditional Knowledge and Biological Materials',
    jurisdiction: 'India',
    topic: 'Patentability',
    provision: 'IPO Traditional Knowledge Guidelines Clause 5.1 - 5.4',
    version_date: '2012-10-29',
    summary: 'Defines inventive step hurdles, requirement of synergism proof, and rejection criteria for traditional preparations.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] IPO TK Guidelines: 1. If the combination of herbs is already known in Charaka Samhita or Bhavaprakasha, it lacks novelty. 2. If known plants with known properties are combined, it is presumed obvious under Section 3(e) unless applicant proves non-obvious synergistic interaction. 3. Novel isolation processes, novel drug delivery carriers (e.g. liposomal curcumin, phytosomes), and novel synthetic derivatives may satisfy patentability criteria.',
    url_placeholder: 'https://ipindia.gov.in',
    dataset_origin: 'ipindia',
    authoritative_source_url: 'https://ipindia.gov.in',
    tags: ['tk guidelines', 'inventive step', 'novelty', 'phytosomes', 'drug delivery', 'patent criteria'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-INT-001',
    authority: 'United States Food and Drug Administration (US FDA) / CDER',
    title: 'Guidance for Industry: Botanical Drug Development (Final Guidance)',
    jurisdiction: 'International',
    topic: 'International / Export',
    provision: 'FDA-2016-D-2443 / 21 CFR Part 312',
    version_date: '2016-12-01',
    summary: 'US FDA requirements for botanical drugs: multi-batch raw material consistency, fingerprint chromatography, CMC validation, and Phase I-III IND/NDA.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] US FDA Botanical Drug Guidance: Ayurvedic formulations seeking prescription drug status in the US must file an Investigational New Drug (IND) application. FDA accepts prior human experience in India as supportive safety data for early phase trials, but requires strict raw botanical source control (GAP - Good Agricultural Practices), chromatographic batch-to-batch fingerprints, and randomized clinical efficacy endpoints.',
    url_placeholder: 'https://fda.gov',
    dataset_origin: 'international',
    authoritative_source_url: 'https://fda.gov',
    tags: ['us fda', 'botanical drug', 'export', 'ind', 'cmc', 'fingerprint chromatography'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-INT-002',
    authority: 'United States Patent and Trademark Office (USPTO)',
    title: '35 U.S. Code § 101 & § 102 — Natural Products Doctrine and Prior Art',
    jurisdiction: 'International',
    topic: 'Patentability',
    provision: '35 U.S.C. 101 (Myriad/Alice Guidance) & 102 (AIA Prior Art)',
    version_date: '2019-01-07',
    summary: 'Naturally occurring botanical compounds are patent-ineligible unless chemically altered or formulated with markedly different characteristics.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] 35 U.S.C. 101: Under the Alice/Myriad framework, products of nature (unaltered raw extracts, standard plant powders) are ineligible subject matter. To secure US patent claims, Ayurvedic innovators must claim specific synergistic compositions, novel structural derivatives, or specific functionalized delivery matrices possessing "markedly different characteristics" from the natural botanical.',
    url_placeholder: 'https://uspto.gov',
    dataset_origin: 'international',
    authoritative_source_url: 'https://uspto.gov',
    tags: ['uspto', '35 usc 101', 'natural products doctrine', 'alice', 'us patent', 'prior art'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-INT-003',
    authority: 'European Patent Office (EPO)',
    title: 'European Patent Convention (EPC) — Herbal Formulations & Medical Use Claims',
    jurisdiction: 'International',
    topic: 'International / Export',
    provision: 'EPC Article 52(2), 53(c) & Article 54(5)',
    version_date: '2020-03-01',
    summary: 'Methods of treatment are excluded, but specific first and second medical use claims (Art 54(5)) for novel botanical fractions are permitted.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] EPC Art 54(5): Direct methods for treatment of the human body are excluded under Art 53(c). However, "Substance X for use in the treatment of Disease Y" (second medical use format) is acceptable for novel, non-obvious herbal fractions with verified preclinical efficacy. Prior published Ayurvedic texts in TKDL or public domain serve as state-of-the-art novelty destroyers under Art 54(2).',
    url_placeholder: 'https://epo.org',
    dataset_origin: 'international',
    authoritative_source_url: 'https://epo.org',
    tags: ['epo', 'epc', 'second medical use', 'european patent', 'novelty'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-INT-004',
    authority: 'European Medicines Agency (EMA) / HMPC',
    title: 'Directive 2004/24/EC — Traditional Herbal Medicinal Products Directive (THMPD)',
    jurisdiction: 'International',
    topic: 'International / Export',
    provision: 'Directive 2004/24/EC Article 16a to 16i',
    version_date: '2004-03-31',
    summary: 'Simplified registration for traditional herbal medicines with at least 30 years of safe traditional use (with at least 15 years documented in EU).',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] EMA THMPD Directive: Allows simplified herbal registration without full clinical trials if applicant proves continuous traditional medicinal use for at least 30 years preceding the application, of which at least 15 years must be within the European Union. Ayurvedic products lacking 15-year EU sales history must undergo standard Well-Established Use (WEU) or full marketing authorization.',
    url_placeholder: 'https://ema.europa.eu',
    dataset_origin: 'international',
    authoritative_source_url: 'https://ema.europa.eu',
    tags: ['ema', 'thmpd', 'traditional herbal', 'european union', 'export compliance'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-INT-005',
    authority: 'World Intellectual Property Organization (WIPO)',
    title: 'WIPO Treaty on Intellectual Property, Genetic Resources and Associated Traditional Knowledge',
    jurisdiction: 'International',
    topic: 'Traditional Knowledge / TKDL',
    provision: 'WIPO Diplomatic Conference Treaty (2024)',
    version_date: '2024-05-24',
    summary: 'Historic treaty requiring mandatory patent disclosure of source country and Indigenous/TK provider for inventions based on genetic resources.',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] WIPO 2024 GR/TK Treaty: Contracting patent offices worldwide must require patent applicants to disclose the country of origin or source of genetic resources and associated traditional knowledge. Non-compliance triggers procedural invalidation or post-grant revocation mechanisms, harmonizing global biopiracy safeguards with India’s BD Act.',
    url_placeholder: 'https://wipo.int',
    dataset_origin: 'international',
    authoritative_source_url: 'https://wipo.int',
    tags: ['wipo', 'genetic resources', 'mandatory disclosure', 'treaty', 'biopiracy'],
    is_mock: true,
  },
  {
    source_id: 'MOCK-INT-006',
    authority: 'Secretariat of the Convention on Biological Diversity (CBD)',
    title: 'Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits',
    jurisdiction: 'International',
    topic: 'ABS / Biodiversity',
    provision: 'Articles 5, 6, 15, 16 & 17 (ABS Clearing-House)',
    version_date: '2014-10-12',
    summary: 'International treaty requiring compliance with domestic ABS legislation of provider countries (Prior Informed Consent and Mutually Agreed Terms).',
    content:
      '[MOCK EXCERPT - FOR SIH DEMO] Nagoya Protocol: Exporters and international researchers utilizing Indian medicinal flora (e.g. Ashwagandha, Tulsi, Brahmi) must secure Prior Informed Consent (PIC) and Mutually Agreed Terms (MAT) via NBA India. Internationally Recognized Certificates of Compliance (IRCC) generated through the ABS Clearing-House verify legitimate provenance.',
    url_placeholder: 'https://cbd.int',
    dataset_origin: 'international',
    authoritative_source_url: 'https://cbd.int',
    tags: ['nagoya protocol', 'pic', 'mat', 'ircc', 'international abs', 'compliance'],
    is_mock: true,
  },
];
